# Generated by Django 6.0.3 on 2026-04-16 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255, unique=True)),
                ('director', models.CharField(max_length=100)),
                ('released_year', models.IntegerField()),
                ('story', models.TextField()),
                ('budget', models.DecimalField(decimal_places=4, max_digits=10)),
                ('language', models.CharField(choices=[('Eng', 'English'), ('Beng', 'Bengali'), ('Span', 'Spanish'), ('Fre', 'French')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=50)),
                ('review', models.TextField(max_length=500)),
                ('rating', models.FloatField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies.movies')),
            ],
        ),
    ]
